# Generated by Django 4.2.1 on 2023-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_chef_chef_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='intro',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='making',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='nut',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='protein',
            field=models.TextField(),
        ),
    ]
