# Generated by Django 4.2.1 on 2023-09-28 07:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_recipes_ingredients_alter_recipes_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='intro',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='making',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='nut',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='protein',
            field=tinymce.models.HTMLField(),
        ),
    ]
