# Generated by Django 4.2.1 on 2023-10-21 10:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='chef_info',
            field=tinymce.models.HTMLField(),
        ),
    ]
