# Generated by Django 4.2.1 on 2023-10-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_chef_chef_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='recipe_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modules.recipes'),
        ),
    ]
