# Generated by Django 4.2.1 on 2023-10-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_chef_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
