# Generated by Django 4.2.1 on 2023-10-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_recipes_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='protein',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='nut',
            field=models.ImageField(default=None, max_length=500, null=True, upload_to='recipess'),
        ),
    ]
