# Generated by Django 4.2.1 on 2023-10-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_chef_cusine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='recipe_name',
        ),
    ]
