# Generated by Django 4.2.1 on 2023-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_remove_chef_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='nation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
