# Generated by Django 4.2.1 on 2023-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0016_chef_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cook_time',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='prep_time',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='servings',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='total_time',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
